educa/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from courses.views import CourseListView


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main/', include('reception.urls')),
    path('finance/', include('finance.urls')),
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

handler500 = 'reception.views.main.error_500'
handler404 = 'reception.views.main.error_404'

reception/urls.py
from django.urls import path
from reception.views import actions, groups, main, students


app_name = 'reception'

urlpatterns = [
    path('reception/', main.reception, name='reception'),
    path('first-lesson/', main.first_lesson, name='first_lesson'),
    path('second-lesson/', main.second_lesson, name='second_lesson'),
    path('lost/', main.lost, name='lost'),

    path('add-student/', students.add_student, name='add_student'),
    path('edit-student/<int:student_id>/', students.edit_student, name='edit_student'),
    path('delete-student/<int:student_id>/', students.delete_student, name='delete_student'),
    path('transfer_student_to_group/<int:student_id>/',
         students.transfer_student_to_group,
         name='transfer_student_to_group'),

    path('star/<int:student_id>', actions.send2second_lesson, name='send2second_lesson'),
    path('star-o/<int:student_id>', actions.send2first_lesson, name='send2first_lesson'),
    path('r/<int:student_id>', actions.student_r, name='student_r'),
    path('student_podo/<int:student_id>', actions.student_podo, name='student_podo'),
    path('student-pay/<int:student_id>', actions.student_pay, name='student_pay'),
    path('student-want2pay/<int:student_id>', actions.student_want2pay, name='student_want2pay'),

    path('group/ajax/get/', groups.get_group, name="get_ajax_group"),
    path('groups/', groups.groups, name='groups'),
    path('group-show/<int:group_id>', groups.group_show, name='group_show'),
    path('group-edit/<int:group_id>', groups.group_edit, name='group_edit'),
    path('add-group/', groups.add_group, name='add_group'),
    path('new-groups/', groups.new_groups, name='new_groups'),
]

students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views


urlpatterns = [
    path('',
         views.StudentIndex.as_view(),
         name='index'),
    path('marks/',
         views.StudentMarks.as_view(),
         name='marks'),
    path('register/',
         views.StudentRegistrationView.as_view(),
         name='student_registration'),
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('course/<pk>/',
         cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
         name='student_course_detail'),
    path('course/<pk>/<module_id>/',
         cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
         name='student_course_detail_module'),

]

teacher/urls.py
from django.urls import path
from . import views


app_name = 'teacher'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('student/<int:id>/', views.student, name='student'),
    path('group-students/<int:group_id>/', views.group_students, name='group-students'),
    path('group-students-table/<int:group_id>/', views.group_students_table, name='group-students-table'),
]

students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                    widget=forms.HiddenInput)

reception/views/students.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from refs.models import Phones
from reception.models import Students, Group, StudentLessons, StudentTransferGroup
from reception.forms import StudentsCreateForm
from finance.models import Payment


def add_student(request):
    form = StudentsCreateForm(data=request.GET)

    if request.method == 'POST':
        # Форма отправлена.
        form = StudentsCreateForm(data=request.POST)

        if form.is_valid():
            new_student = form.save(commit=False)
            new_student.created_by = request.user
            new_student.status = 0
            new_student.save()

            student_data = request.POST
            phone_list = student_data.getlist('phone')
            relation_list = student_data.getlist('relation')
            if len(phone_list) > 1:
                for i in range(len(phone_list)):
                    phone = Phones(name=relation_list[i], number=phone_list[i])
                    phone.save()
                    new_student.phone.add(phone)
                new_student.save()
            else:
                messages.success(request, 'Student is not created')
                # new_student.rollback()
                return redirect('reception:reception')

            messages.success(request, 'Student added successfully')
            return redirect('reception:reception')

    title = 'Add student'
    return render(request, 'reception/student_add_edit.html', {
        'form': form,
        'title': title
    })


def edit_student(request, student_id):

    student = get_object_or_404(Students, id=student_id)
    form = StudentsCreateForm(request.POST or None, instance=student)
    if request.method == 'POST':
        # Форма отправлена.
        form = StudentsCreateForm(data=request.POST, instance=student)
        if form.is_valid():
            student = form.save()
            student.save()

            studentData = request.POST
            phoneList = studentData.getlist('phone')
            relationList = studentData.getlist('relation')
            for i in range(len(phoneList)):
                if relationList[i] != '' or phoneList[i] != '':
                    phone = Phones(name=relationList[i], number=phoneList[i])
                    phone.save()
                    student.phone.add(phone)

            messages.success(request, 'Student added successfully')
            return redirect('reception:reception')
    title = 'Edit student'
    return render(request, 'reception/student_add_edit.html', {
        'title': title,
        'form': form
    })


def delete_student(request, student_id):
    student = get_object_or_404(Students, id=student_id)

    if request.method == "POST":
        # delete object
        if student.status == 30:
            student.delete()
        else:
            student.status = 30
            student.save()
        messages.error(request, 'Student successfully deleted')
        return redirect("reception:reception")

    return render(request, "reception/studentDelete.html", {
        'student': student
    })


def transfer_student_to_group(request, student_id):

    student = Students.objects.filter(id=student_id).get()
    if request.method == 'POST':
        formData = request.POST
        group_id = formData.get('group_id')
        student.group_id = group_id
        student.status = 1
        student.save()
        dateStr = formData.get('date')
        date = datetime.datetime.strptime(dateStr, "%Y-%m-%d").date()

        transfer = StudentTransferGroup.objects.filter(student_id=student_id, status=True).first()
        if transfer:
            transfer.status = False
            transfer.save()

        group = Group.objects.get(id=group_id)
        sequence = group.get_current_student_count()

        StudentTransferGroup.objects.create(
            student_id=student_id,
            group_id=group_id,
            date=date,
            sequence=sequence+1,
            status=True
        )
        StudentLessons.objects.create(
            student=student,
            group=group,
            date=date,
            is_first=True
        )
        # next_month = datetime.datetime.strptime(dateStr, "%Y-%m-%d").date()
        next_month = datetime.datetime(date.year + int(date.month / 12), ((date.month % 12) + 1), 1)
        Payment.objects.create(
            date=date,
            student=student,
            status=0,
            from_date=date,
            to_date=next_month,
        )

    groups = Group.objects.all()

    return render(request,
                  'reception/student2Group.html',
                  {
                      'student': student,
                      'groups': groups
                  })

students/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from courses.models import Course
from .forms import CourseEnrollForm


class StudentIndex(LoginRequiredMixin, ListView):
    template_name = 'students/student/index.html'

    def get_queryset(self):
        return ''


class StudentMarks(LoginRequiredMixin, ListView):
    template_name = 'students/student/marks.html'

    def get_queryset(self):
        # qs = super(StudentCourseListView, self).get_queryset()
        # return qs.filter(students__in=[self.request.user])
        return ''


class StudentRegistrationView(CreateView):
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('student_course_list')

    def form_valid(self, form):
        result = super(StudentRegistrationView,
                       self).form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'],
                            password=cd['password1'])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super(StudentEnrollCourseView,
                     self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('student_course_detail',
                            args=[self.course.id])


class StudentCourseDetailView(DetailView):
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        qs = super(StudentCourseDetailView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super(StudentCourseDetailView,
                        self).get_context_data(**kwargs)
        # get course object
        course = self.get_object()
        if 'module_id' in self.kwargs:
            # get current module
            context['module'] = course.modules.get(
                                    id=self.kwargs['module_id'])
        else:
            # get first module
            context['module'] = course.modules.all()[0]
        return context


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/course/list.html'

    def get_queryset(self):
        qs = super(StudentCourseListView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])

teacher/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from reception.models import Students, Group


def index(request):
    breadcrumbs = [
        {
            'name': 'Главная',
            'url': '/',
            'class': '',
        },
    ]
    bodyclass = 'sidebar-collapse'
    title = 'test'
    return render(request,
                  'teacher/index.html',
                  {title: title,
                   'breadcrumbs': breadcrumbs,
                   'bodyclass': bodyclass})


def student(request, id):
    student = get_object_or_404(Students, id=id)
    data_dict = {
        'student': student
    }
    return render(request,
                  'teacher/student.html',
                  data_dict)


def group_students(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    students = get_list_or_404(Students, group_id=group_id)
    data_dict = {
        'group': group,
        'students': students
    }
    return render(request,
                  'teacher/group_students.html',
                  data_dict)


def group_students_table(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    students = get_list_or_404(Students, group_id=group_id)
    data_dict = {
        'group': group,
        'students': students
    }
    return render(request,
                  'teacher/group_students_table.html',
                  data_dict)


def dashboard(request):
    return render(request,
                  'teacher/dashboard.html')

templates/teacher/group_students.html
{% extends "base.html" %}
{% load static %}

{% block title %}Group students{% endblock %}

{% block nav_sidebar %}
<style>
.content-wrapper, .main-footer, .main-header {
    margin-left: 0px !important;
}
</style>
{% endblock %}

{% block content %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Group Students</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'teacher:index' %}">Home</a></li>
                    <li class="breadcrumb-item">Group Students</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        <div class="col">
            <a href="{% url 'teacher:group-students-table' group_id=group.id %}" class="btn btn-default">Show as table</a>
            <a href="{% url 'teacher:group-students' group_id=group.id %}" class="btn btn-default">Show as card</a>
        </div>
    </div>
    <!-- Default box -->
    <div class="card card-solid">
        <div class="card-body pb-0">
            <div class="row d-flex align-items-stretch">
                {% for student in students%}
                <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
                    <div class="card bg-light">
                        <div class="card-header text-muted border-bottom-0">
                            Student
                        </div>
                        <div class="card-body pt-0">
                            <div class="row">
                                <div class="col-12">
                                    <h2 class="lead"><b>{{student.full_name}}</b></h2>
                                    <p class="text-muted text-sm"><b>Note: </b> {{student.note}} </p>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span>
                                            Phone #:
                                            {% for phone in student.phone.all %}
                                            <span class="badge badge-lg badge-primary">{{phone}}</span>
                                            {% endfor %}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="text-right">
                                <a href="{% url 'teacher:student' student.id%}" class="btn btn-sm btn-primary">
                                    <i class="fas fa-user"></i> View Profile
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>
{% endblock %}

templates/teacher/group_students_table.html
{% extends "base.html" %}

{% block title %}SE - Group students{% endblock %}

{% block nav_sidebar %}
<style>
.content-wrapper, .main-footer, .main-header {
    margin-left: 0px !important;
}
</style>
{% endblock %}

{% block content %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'teacher:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Group students</li>
            </ol>
        </div>
    </div><!-- /.container-fluid -->
</section>

<h1>Group students</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Full name</th>
            <th>Phone</th>
            <th>From date</th>
            <th>To date</th>
            <th>Lessons</th>
            <th>Info</th>
            <th>Note</th>
            <th>Paid</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        {% if student.is_podo %}
        <style>
            .podo {
                background-color: #999;
            }
        </style>
        {%endif%}
        <tr class="podo">
            <td>{{student.created_time}}</td>
            <td>{{student.full_name}}</td>
            <td>
                {% for phone in student.phone.all %}
                <span class="badge badge-primary">{{phone}}</span>
                {% endfor %}
            </td>
            <td>{{student.payment_student.from_date}}</td>
            <td>{{student.payment_student.to_date}}</td>
            <td>12</td>
            <td>
                <span class="badge badge-info">Group: Current</span>
                <span class="badge badge-info">{{student.payment_student.from_date}}</span>
                <span class="badge badge-primary">{{student.payment_student.to_date}}</span>
                <span class="badge badge-primary">Paid: 0</span>
                <span class="badge badge-primary">Should pay: 0 UZS</span>
                <a href="javascript:void(0);" class="btn btn-success pay" data-toggle="modal" data-target="#modal-default"
                data-student-id="{{student.id}}">
                    Pay
                </a>
            </td>
            <td>{{student.note}}</td>
            <td>
                <div class="panel panel-success">
                  <div class="panel-body">
                    <span class="badge badge-info">{{student.group.name}}</span>
                    <span class="badge badge-info">{{student.group.teacher.full_name}}</span>
                    <span class="badge badge-primary">{{student.group.days}} {{student.group.times}}</span>
                    <span class="badge badge-primary">{{student.group.level}}: {{student.group.sub}}</span>
                  </div>
                </div>
            </td>
            <td>

                <!--Pul toliman desa shu knopka bosiladi-->
                <a href="javascript:void(0);" class="w2p" data-toggle="modal" data-target="#myModal"
                    data-student-id="{{student.id}}">
                    Pay
                    <i class="fa fa-money" aria-hidden="true"></i>
                </a>

                <a href="{% url 'reception:edit_student' student_id=student.id %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'reception:delete_student' student_id=student.id %}"><i class="fas fa-trash"></i></a>
                <a href="{% url 'reception:student_podo' student_id=student.id %}">
                    PODO
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="modal-default" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Payment</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="" class="payment-form">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <label for="amount">Amount</label>
                        <input id="amount" type="number" name="amount" class="form-control" value="450000">
                    </div>
                    <div class="input-group mb-3">
                        <label for="type">Payment type</label>
                        <select name="payment_type" id="type" class="form-control">
                            <option value="1">Plastic</option>
                            <option value="2" selected>Cash</option>
                            <option value="3">MOT</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <label for="status">Payment status</label>
                        <select name="payment_status" class="form-control" id="status">
                            <option value="0">Not paid</option>
                            <option value="1" selected>Should pay</option>
                            <option value="2">Full paid</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <label for="date">Date</label>
                        <input type="date" id="date" name="date" class="form-control" placeholder="01.01.2021">
                    </div>

                    <input type="submit" class="btn btn-primary" value="Pay">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Close</button>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Date of payment</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body">
        <form method="post" action="" class="payment-form">
            {% csrf_token %}

            <div class="input-group mb-3">
                <label for="date-w">Date</label>
                <input type="date" id="date-w" name="date" class="form-control" placeholder="01.01.2021">
            </div>
            <input type="submit" class="w2p btn btn-primary" value="Save">
        </form>
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('.w2p').click(function(){
        student_id = $(this).attr('data-student-id');
        $('.payment-form').attr('action', '/main/student_want2pay/'+student_id);
    });
});
</script>
{% endblock %}

templates/teacher/student.html
{% extends "base.html" %}
{% load static %}

{% block title %}Student{% endblock %}

{% block nav_sidebar %}
<style>
.content-wrapper, .main-footer, .main-header {
    margin-left: 0px !important;
}
</style>
{% endblock %}

{% block content %}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Profile</h1>
                <h1>
                    <a href="{% url 'reception:edit_student' student_id=student.id %}" class="btn btn-success">Update student</a>
                    <a href="" class="btn btn-warning">Change password</a>
                    <a href="" class="btn btn-primary">Print login</a>
                    <a href="" class="btn btn-info">Print one time paper</a>
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'teacher:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">User Profile</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="/media/images/profile.png"
                                 alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{student.last_name}} {{student.first_name}}</h3>

                        <p class="text-muted text-center">Student</p>

                        <ul class="list-group list-group-unbordered mb-3">
                            {% for phone in student.phone.all %}
                                <li class="list-group-item">
                                    <b>{{phone}}</b>
                                </li>
                            {% endfor %}
                            <li class="list-group-item">
                                <b>Date Birth: </b>{{student.date_birth}}
                            </li>
                        </ul>

<!--                        <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>-->
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">About Me</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <strong><i class="fas fa-book mr-1"></i> Group</strong>

                        <p class="text-muted">
                            {{student.group}}
                        </p>

                        <hr>

                        <strong><i class="fas fa-map-marker-alt mr-1"></i> Status</strong>

                        <p class="text-muted">{{student.status}}</p>

                        <hr>

                        <strong><i class="fas fa-pencil-alt mr-1"></i> Level</strong>

                        <p class="text-muted">
                            <span class="tag tag-primary">{{student.level}}</span>
                        </p>

                        <hr>

                        <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

                        <p class="text-muted">
                            {{student.note}}
                        </p>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header p-2">
                        <h2>Payments</h2>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="active tab-pane" id="activity">
                                <!-- Post -->
                                <div class="post">
                                    <div class="user-block">
                                        <img class="img-circle img-bordered-sm" src="/media/images/user1.jpg"
                                             alt="user image">
                                        <span class="username">
                                          <a href="#">Jonathan Burke Jr.</a>
                                          <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                        </span>
                                        <span class="description">Shared publicly - 7:30 PM today</span>
                                    </div>
                                    <!-- /.user-block -->
                                    <p>
                                        Lorem ipsum represents a long-held tradition for designers,
                                        typographers and the like. Some people hate it and argue for
                                        its demise, but others ignore the hate as they create awesome
                                        tools to help create filler text for everyone from bacon lovers
                                        to Charlie Sheen fans.
                                    </p>

                                    <p>
                                        <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i>
                                            Share</a>
                                        <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i>
                                            Like</a>
                                        <span class="float-right">
                                          <a href="#" class="link-black text-sm">
                                            <i class="far fa-comments mr-1"></i> Comments (5)
                                          </a>
                                        </span>
                                    </p>

                                    <input class="form-control form-control-sm" type="text"
                                           placeholder="Type a comment">
                                </div>
                                <!-- /.post -->



                            </div>
                        </div>
                        <!-- /.tab-content -->
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
{% endblock %}