educa/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from courses.views import CourseListView


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main/', include('reception.urls')),
    path('finance/', include('finance.urls')),
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

handler500 = 'reception.views.main.error_500'
handler404 = 'reception.views.main.error_404'

reception/urls.py
from django.urls import path
from reception.views import actions, groups, main, students


app_name = 'reception'

urlpatterns = [
    path('reception/', main.reception, name='reception'),
    path('first-lesson/', main.first_lesson, name='first_lesson'),
    path('second-lesson/', main.second_lesson, name='second_lesson'),
    path('lost/', main.lost, name='lost'),

    path('add-student/', students.add_student, name='add_student'),
    path('edit-student/<int:student_id>/', students.edit_student, name='edit_student'),
    path('delete-student/<int:student_id>/', students.delete_student, name='delete_student'),
    path('transfer_student_to_group/<int:student_id>/',
         students.transfer_student_to_group,
         name='transfer_student_to_group'),

    path('star/<int:student_id>', actions.send2second_lesson, name='send2second_lesson'),
    path('star-o/<int:student_id>', actions.send2first_lesson, name='send2first_lesson'),
    path('r/<int:student_id>', actions.student_r, name='student_r'),
    path('student_podo/<int:student_id>', actions.student_podo, name='student_podo'),
    path('student-pay/<int:student_id>', actions.student_pay, name='student_pay'),
    path('student-want2pay/<int:student_id>', actions.student_want2pay, name='student_want2pay'),

    path('group/ajax/get/', groups.get_group, name="get_ajax_group"),
    path('groups/', groups.groups, name='groups'),
    path('group-show/<int:group_id>', groups.group_show, name='group_show'),
    path('group-edit/<int:group_id>', groups.group_edit, name='group_edit'),
    path('add-group/', groups.add_group, name='add_group'),
    path('new-groups/', groups.new_groups, name='new_groups'),
]

reception/forms.py
from django import forms
from .models import Students, Group


class StudentsCreateForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ('first_name', 'last_name', 'date_birth',
                  'come_from', 'level', 'prefer_day',
                  'prefer_time', 'group_type', 'is_old', 'note')
        widgets = {
            'note': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
        }


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name',  'group_type', 'teacher',
                  'room', 'level', 'days', 'times',
                  'status', 'place_count', 'sub', 'start_date')

reception/views/actions.py
import datetime
import calendar

from django.shortcuts import redirect, get_object_or_404

from finance.models import Payment, WantPay
from reception.models import Students, StudentLessons


def send2first_lesson(request, student_id):
    student = get_object_or_404(Students, id=student_id)
    student.status = 1
    student.status_p = False
    student.status_r = False
    student.save()
    # TODO: delete StudentLesson
    sl = StudentLessons.objects.filter(
        student=student,
        group=student.group,
        is_first=False,
        is_second=True)
    sl.delete()
    # END-TODO---------
    return redirect('reception:first_lesson')


def send2second_lesson(request, student_id):
    student = get_object_or_404(Students, id=student_id)
    student.status = 2
    student.status_p = False
    student.status_r = False
    student.save()

    s = datetime.date
    today = str(s.today())
    sl = StudentLessons(
        student=student,
        group=student.group,
        is_first=True,
        is_second=False,
        date=today
    )
    sl.save()
    return redirect('reception:second_lesson')


def student_r(request, student_id):
    student = get_object_or_404(Students, id=student_id)
    student.status_r = True
    student.save()
    return redirect('reception:second_lesson')


def student_p(request, student_id):
    student = get_object_or_404(Students, id=student_id)
    student.status_p = True
    student.save()
    return redirect('reception:second_lesson')


# PODO button clicked
def student_podo(request, student_id):
    student = get_object_or_404(Students, id=student_id)
    if student.is_podo:
        student.is_podo = False
    else:
        student.is_podo = True
    print(student.is_podo)
    student.save()
    return redirect('/main/first-lesson')


def next_month_date(d):
    _year = d.year+(d.month//12)
    _month =  1 if (d.month//12) else d.month + 1
    next_month_len = calendar.monthrange(_year, _month)[1]
    next_month = d
    if d.day > next_month_len:
        next_month = next_month.replace(day=next_month_len)
    next_month = next_month.replace(year=_year, month=_month)
    return next_month


def student_pay(request, student_id):
    if request.method == 'POST':
        formData = request.POST
        student = get_object_or_404(Students, id=student_id)
        student.status = 40
        student.save()

        amount = formData['amount']
        payment_status = formData['payment_status']
        payment_type = formData['payment_type']
        date = formData['date']
        from_date = formData['date']
        d = datetime.datetime.strptime(from_date, '%Y-%m-%d')
        to_date = next_month_date(d)
        payment = Payment(
            student=student,
            date=date,
            amount=amount,
            type=payment_type,
            status=payment_status,
            from_date=from_date,
            to_date=to_date,
            want_pay_next_month=False,
        )
        print(payment)
        payment.save()

    return redirect('reception:reception')


def student_want2pay(request, student_id):
    if request.method == 'POST':
        formData = request.POST
        student = get_object_or_404(Students, id=student_id)

        date = formData['date']
        w2p = WantPay(
            student=student,
            date=date,
        )
        # print(payment)
        w2p.save()

    return redirect('reception:reception')

reception/views/groups.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from reception.models import Students, Group, Room, PreferTimes
from reception.forms import GroupCreateForm


def get_group(request):
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        group_id = request.GET.get("group_id", None)
        group = Group.objects.get(pk=group_id)
        # print(group.name)
        if group:
            group_dict = {
                "name": group.name,
                "teacher": group.teacher.full_name(),
                "level": group.level.name,
                "place_count": group.place_count,
            }
            return JsonResponse(group_dict, status=200)
        else:
            return JsonResponse({}, status=404)
    return JsonResponse({}, status=400)


def groups(request):
    groups = Group.objects.all()
    rooms = Room.objects.all()
    times = PreferTimes.objects.all()

    scheduleList = []
    for room in rooms:
        scheduleList.insert(
            room.id,
            {
                'id': room.id,
                'name': room.name,
                'times': [{'class': 'button'} for x in times]
            }
        )

    for group in groups:
        scheduleList[group.room.id-1]['times'][group.times.id-1] = {
            'id': group.id,
            'name': group.name,
            'class': 'full',
        }

    return render(request,
                  'reception/groups.html',
                  {
                      'rooms': rooms,
                      'groups': groups,
                      'times': times,
                      'schedule': scheduleList,
                  })


def add_group(request):
    form = GroupCreateForm(data=request.GET)

    if request.method == 'POST':
        # Форма отправлена.
        form = GroupCreateForm(data=request.POST)

        if form.is_valid():
            group = form.save(commit=False)
            group.created_by = request.user
            group.save()
            messages.success(request, 'Group added successfully')
            # Перенаправляем пользователя на страницу груп.
            return redirect('reception:groups')

    title = 'Add group'
    action_url = reverse('reception:add_group')
    return render(request,
                  'reception/group_add_edit.html',
                  {
                      'action_url': action_url,
                      'title': title,
                      'form': form
                  })


def group_edit(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    form = GroupCreateForm(request.POST or None, instance=group)

    if request.method == 'POST':
        # Форма отправлена.
        form = GroupCreateForm(data=request.POST, instance=group)

        if form.is_valid():
            group = form.save()
            group.save()
            messages.success(request, 'Group edit successfully')
            # Перенаправляем пользователя на страницу груп.
            return redirect('reception:groups')

    title = 'Edit group'
    action_url = reverse('reception:group_edit', kwargs={'group_id': group.id})
    data_dict = {
        'action_url': action_url,
        'title': title,
        'form': form
    }

    return render(request,
                  'reception/group_add_edit.html',
                  data_dict)


def new_groups(request):
    groups = Group.objects.all().order_by('-id')
    return render(request,
                  'reception/new_groups.html',
                  {
                      'groups': groups
                  })


def group_show(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    students = Students.objects.filter(group_id=group_id).all()
    data_dict = {
        'group': group,
        'students': students
    }
    return render(request,
                  'reception/group_students.html',
                  data_dict)

reception/views/students.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from refs.models import Phones
from reception.models import Students, Group, StudentLessons, StudentTransferGroup
from reception.forms import StudentsCreateForm
from finance.models import Payment


def add_student(request):
    form = StudentsCreateForm(data=request.GET)

    if request.method == 'POST':
        # Форма отправлена.
        form = StudentsCreateForm(data=request.POST)

        if form.is_valid():
            new_student = form.save(commit=False)
            new_student.created_by = request.user
            new_student.status = 0
            new_student.save()

            student_data = request.POST
            phone_list = student_data.getlist('phone')
            relation_list = student_data.getlist('relation')
            if len(phone_list) > 1:
                for i in range(len(phone_list)):
                    phone = Phones(name=relation_list[i], number=phone_list[i])
                    phone.save()
                    new_student.phone.add(phone)
                new_student.save()
            else:
                messages.success(request, 'Student is not created')
                # new_student.rollback()
                return redirect('reception:reception')

            messages.success(request, 'Student added successfully')
            return redirect('reception:reception')

    title = 'Add student'
    return render(request, 'reception/student_add_edit.html', {
        'form': form,
        'title': title
    })


def edit_student(request, student_id):

    student = get_object_or_404(Students, id=student_id)
    form = StudentsCreateForm(request.POST or None, instance=student)
    if request.method == 'POST':
        # Форма отправлена.
        form = StudentsCreateForm(data=request.POST, instance=student)
        if form.is_valid():
            student = form.save()
            student.save()

            studentData = request.POST
            phoneList = studentData.getlist('phone')
            relationList = studentData.getlist('relation')
            for i in range(len(phoneList)):
                if relationList[i] != '' or phoneList[i] != '':
                    phone = Phones(name=relationList[i], number=phoneList[i])
                    phone.save()
                    student.phone.add(phone)

            messages.success(request, 'Student added successfully')
            return redirect('reception:reception')
    title = 'Edit student'
    return render(request, 'reception/student_add_edit.html', {
        'title': title,
        'form': form
    })


def delete_student(request, student_id):
    student = get_object_or_404(Students, id=student_id)

    if request.method == "POST":
        # delete object
        if student.status == 30:
            student.delete()
        else:
            student.status = 30
            student.save()
        messages.error(request, 'Student successfully deleted')
        return redirect("reception:reception")

    return render(request, "reception/studentDelete.html", {
        'student': student
    })


def transfer_student_to_group(request, student_id):

    student = Students.objects.filter(id=student_id).get()
    if request.method == 'POST':
        formData = request.POST
        group_id = formData.get('group_id')
        student.group_id = group_id
        student.status = 1
        student.save()
        dateStr = formData.get('date')
        date = datetime.datetime.strptime(dateStr, "%Y-%m-%d").date()

        transfer = StudentTransferGroup.objects.filter(student_id=student_id, status=True).first()
        if transfer:
            transfer.status = False
            transfer.save()

        group = Group.objects.get(id=group_id)
        sequence = group.get_current_student_count()

        StudentTransferGroup.objects.create(
            student_id=student_id,
            group_id=group_id,
            date=date,
            sequence=sequence+1,
            status=True
        )
        StudentLessons.objects.create(
            student=student,
            group=group,
            date=date,
            is_first=True
        )
        # next_month = datetime.datetime.strptime(dateStr, "%Y-%m-%d").date()
        next_month = datetime.datetime(date.year + int(date.month / 12), ((date.month % 12) + 1), 1)
        Payment.objects.create(
            date=date,
            student=student,
            status=0,
            from_date=date,
            to_date=next_month,
        )

    groups = Group.objects.all()

    return render(request,
                  'reception/student2Group.html',
                  {
                      'student': student,
                      'groups': groups
                  })

templates/reception/createGroup.html
{% extends "base.html" %}

{% block title %}SE - Create Student{% endblock %}

{% block content %}
<div class="row">
    <div class="col-8">
        <div class="card card-primary">
            <div class="card-header">
                <div class="card-title">
                    <h3>Create Group</h3>
                </div>
            </div>
            <div class="card-body">
                <form action="." class="post" method="POST">
                    {% csrf_token %}
                    {% if message %}
                        <p class="login-box-msg" style="color: red;">{{ message }}</p>
                    {% endif %}
                    {% for field in form %}
                    <div class="form-group row form-row field-name">
                        <label for="{{form.id_for_label}}" class="col-sm-2 col-form-label">
                            {{ field.label_tag }}
                        </label>
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}

                    <input type="submit" value="Create" class="btn btn-primary">
                    <a href="{% url 'reception:groups' %}" class="btn btn-danger">Back</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/reception/first_second.html
{% extends "base.html" %}

{% block title %}SE - First & Second{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6"><a href="{% url 'reception:first_lesson' %}" class="btn btn-info w-100"><h2>First Lesson</h2></a></div>
    <div class="col-6"><a href="{% url 'reception:second_lesson' %}" class="btn btn-success w-100"><h2>Second Lesson</h2></a></div>
</div>

<h2>{{title}}</h2>
<br>
<br>
<br>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Full name</th>
            <th>Phone</th>
            <th>From date</th>
            <th>To date</th>
            <th>Lessons</th>
            <th>Info</th>
            <th>Note</th>
            <th>Paid</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        {% if student.is_podo %}
        <style>
            .podo {
                background-color: #999;
            }
        </style>
        {%endif%}
        <tr class="podo">
            <td>{{student.created_time}}</td>
            <td>{{student.full_name}}</td>
            <td>
                {% for phone in student.phone.all %}
                <span class="badge badge-primary">{{phone}}</span>
                {% endfor %}
            </td>
            <td>{{student.payment_student.from_date}}</td>
            <td>{{student.payment_student.to_date}}</td>
            <td>12</td>
            <td>
                <span class="badge badge-info">Group: Current</span>
                <span class="badge badge-info">{{student.payment_student.from_date}}</span>
                <span class="badge badge-primary">{{student.payment_student.to_date}}</span>
                <span class="badge badge-primary">Paid: 0</span>
                <span class="badge badge-primary">Should pay: 0 UZS</span>
                <a href="javascript:void(0);" class="btn btn-success pay" data-toggle="modal" data-target="#modal-default"
                data-student-id="{{student.id}}">
                    Pay
                    <i class="fa fa-money" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{student.note}}</td>
            <td>
                <div class="panel panel-success">
                  <div class="panel-body">
                    <span class="badge badge-info">{{student.group.name}}</span>
                    <span class="badge badge-info">{{student.group.teacher.full_name}}</span>
                    <span class="badge badge-primary">{{student.group.days}} {{student.group.times}}</span>
                    <span class="badge badge-primary">{{student.group.level}}: {{student.group.sub}}</span>
                  </div>
                </div>
            </td>
            <td>
                {%if student.status_r %}
                <a href="javascript:void(0);"
                   style="border:1px solid #aaa; padding:3px 10px; border-radius:50%; background-color:#ff0000; color: #ccc;">
                    R
                </a>
                {%else%}
                <a href="javascript:void(0);"
                   style="border:1px solid #aaa; padding:3px 10px; border-radius:50%;">
                    R
                </a>
                {%endif%}
                {%if student.status_p %}
                    <a href="javascript:void(0);" style="border:1px solid #aaa; padding:4px 10px; border-radius:50%; background-color:#00ff00; color: #333;">
                        <i class="fas fa-running"></i>
                    </a>
                {%else%}
                    <a href="javascript:void(0);" style="border:1px solid #aaa; padding:4px 10px; border-radius:50%;">
                        <i class="fas fa-running"></i>
                    </a>
                {%endif%}
                <!--Second Lesson-->
                <!--Pul toliman desa shu knopka bosiladi-->
                <a href="javascript:void(0);" class="want-pay" data-toggle="modal" data-target="#myModal"
                    data-student-id="{{student.id}}">
                    Pay
                    <i class="fa fa-money" aria-hidden="true"></i>
                </a>
                {%if lesson == 1%}
                <a href="{% url 'reception:send2second_lesson' student_id=student.id %}">
                    next<i class="fa fa-star-o" aria-hidden="true"></i>
                </a>
                {%else%}
                <a href="{% url 'reception:send2first_lesson' student_id=student.id %}">
                    <i class="fas fa-star"></i>
                </a>
                {%endif%}
                <a href="{% url 'reception:edit_student' student_id=student.id %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'reception:delete_student' student_id=student.id %}"><i class="fas fa-trash"></i></a>
                <a href="{% url 'reception:student_podo' student_id=student.id %}">
                    PODO
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="modal-default" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Payment</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="" class="payment-form">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <label for="amount">Amount</label>
                        <input id="amount" type="number" name="amount" class="form-control" value="450000">
                    </div>
                    <div class="input-group mb-3">
                        <label for="type">Payment type</label>
                        <select name="payment_type" id="type" class="form-control">
                            <option value="1">Plastic</option>
                            <option value="2" selected>Cash</option>
                            <option value="3">MOT</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <label for="status">Payment status</label>
                        <select name="payment_status" class="form-control" id="status">
                            <option value="0">Not paid</option>
                            <option value="1" selected>Should pay</option>
                            <option value="2">Full paid</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <label for="date">Date</label>
                        <input type="date" id="date" name="date" class="form-control" placeholder="01.01.2021">
                    </div>

                    <input type="submit" class="btn btn-primary" value="Pay">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Close</button>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Date of payment</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>

      </div>
      <div class="modal-body">
        <form method="post" action="" class="payment-form">
        {% csrf_token %}

        <div class="input-group mb-3">
            <label for="date-w">Date</label>
            <input type="date" id="date-w" name="date" class="form-control" placeholder="01.01.2021">
        </div>


    </form>
      </div>
      <div class="modal-footer">
          <input type="submit" class="btn btn-primary" value="Save">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('.pay').click(function(){
        student_id = $(this).attr('data-student-id');
        console.log(student_id)
        $('.payment-form').attr('action', '/main/student-pay/'+student_id);
    });
});
</script>
{% endblock %}

templates/reception/index.html
{% extends "base.html" %}

{% block title %}SE - Reception{% endblock %}

{% block content %}
<h2>Receptions</h2>
<a class="btn btn-primary" href="{% url 'reception:add_student' %}">Create reception</a>
<br>
<br>
<br>
<div class="box box-info">
    <div class="box-body">
        <form class="form">
    <div class="row">
        <div class="col-md-12">
            <h4>Search and Filter</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Enter ...">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Date:</label>

                <div class="input-group date">
                  <input type="text" class="form-control pull-right" id="datepicker">
                </div>
                <!-- /.input group -->
              </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
              <label>Type</label>
              <select class="form-control">
                <option>Select</option>
                <option value="0">0</option>
              </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
              <label>Time</label>
              <select class="form-control">
                <option>Select</option>
                <option>option 2</option>
                <option>option 3</option>
                <option>option 4</option>
                <option>option 5</option>
              </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
              <label>Level</label>
              <select class="form-control">
                <option>Select</option>
                <option>option 2</option>
                <option>option 3</option>
                <option>option 4</option>
                <option>option 5</option>
              </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
              <label>Sub</label>
              <select class="form-control">
                <option>Select</option>
                <option>option 2</option>
                <option>option 3</option>
                <option>option 4</option>
                <option>option 5</option>
              </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
              <label>Group Type</label>
              <select class="form-control">
                <option>Select</option>
                <option>option 2</option>
                <option>option 3</option>
                <option>option 4</option>
                <option>option 5</option>
              </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
              <label>Is Old</label>
              <select class="form-control">
                <option>Select</option>
                <option>option 2</option>
                <option>option 3</option>
                <option>option 4</option>
                <option>option 5</option>
              </select>
            </div>
        </div>
    </div>
</form>
    </div>
</div>
<script src="https://adminlte.io/themes/AdminLTE/bower_components/jquery/dist/jquery.min.js"></script>
<script src="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script>
  $(function () {
    $('#datepicker').datepicker()
  })
</script>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Full name</th>
            <th>Phone</th>
            <th>Level</th>
            <th>Prefer Time</th>
            <th>Group Type</th>
            <th>Note</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
        <tr>
            <td>{{student.created_time}}</td>
            <td>{{student.full_name}}</td>
            <td>
                {% for phone in student.phone.all %}
                <span class="badge badge-primary">{{phone}}</span>
                {% endfor %}
            </td>
            <td>{{student.level}}</td>
            <td>
                {% for prefer_time in student.prefer_time.all %}
                    <span class="badge badge-info">{{prefer_time}}</span>
                {% endfor %}
            </td>
            <td>{{student.group_type}}</td>
            <td>{{student.note}}</td>
            <td>
                <a href="javascript:void(0);" class="rounded-button">R</a>
                <a href="{% url 'reception:transfer_student_to_group' student_id=student.id %}" class="rounded-button">
                    T
                </a>
                <a href="{% url 'reception:edit_student' student_id=student.id %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'reception:delete_student' student_id=student.id %}"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}