educa/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from courses.views import CourseListView


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('main/', include('reception.urls')),
    path('finance/', include('finance.urls')),
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

handler500 = 'reception.views.main.error_500'
handler404 = 'reception.views.main.error_404'

reception/urls.py
from django.urls import path
from reception.views import actions, groups, main, students


app_name = 'reception'

urlpatterns = [
    path('reception/', main.reception, name='reception'),
    path('first-lesson/', main.first_lesson, name='first_lesson'),
    path('second-lesson/', main.second_lesson, name='second_lesson'),
    path('lost/', main.lost, name='lost'),

    path('add-student/', students.add_student, name='add_student'),
    path('edit-student/<int:student_id>/', students.edit_student, name='edit_student'),
    path('delete-student/<int:student_id>/', students.delete_student, name='delete_student'),
    path('transfer_student_to_group/<int:student_id>/',
         students.transfer_student_to_group,
         name='transfer_student_to_group'),

    path('star/<int:student_id>', actions.send2second_lesson, name='send2second_lesson'),
    path('star-o/<int:student_id>', actions.send2first_lesson, name='send2first_lesson'),
    path('r/<int:student_id>', actions.student_r, name='student_r'),
    path('student_podo/<int:student_id>', actions.student_podo, name='student_podo'),
    path('student-pay/<int:student_id>', actions.student_pay, name='student_pay'),
    path('student-want2pay/<int:student_id>', actions.student_want2pay, name='student_want2pay'),

    path('group/ajax/get/', groups.get_group, name="get_ajax_group"),
    path('groups/', groups.groups, name='groups'),
    path('group-show/<int:group_id>', groups.group_show, name='group_show'),
    path('group-edit/<int:group_id>', groups.group_edit, name='group_edit'),
    path('add-group/', groups.add_group, name='add_group'),
    path('new-groups/', groups.new_groups, name='new_groups'),
]

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Admin</a>
        </li>
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}

    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            {% block user_info %}
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-user fa-2x"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    {% firstof request.user.get_short_name request.user.get_username %}
                                    <span class="float-right text-sm text-danger"><i class="fas fa-online"></i></span>
                                </h3>
                                <p class="text-sm"><small>{% trans 'Member since' %} :</small></p>
                                <p class="text-sm text-muted">
                                    <i class="far fa-clock mr-1"></i>
                                    <small>{{ request.user.date_joined }}</small>
                                </p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <div class="dropdown-footer">
                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                           class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-danger btn-sm">
                            {%trans 'Sign out'%}
                        </a>
                    </div>

                </div>
            </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
    {% endblock nav_custom_menu %}

    {% endblock %}
</nav>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
{%load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="/" class="brand-link">
            {% block logo_text %}<span class="brand-text font-weight-light">Summit Education </span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% avatar_url size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{% firstof request.user.get_full_name request.user.username %}</a>
        </div>
      </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            {% block nav_links_outer %}


            {% block nav_links %}
                <li class="nav-item has-tree-view ">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-object-group"></i> <p>Main Actions</p>
                        <p><i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview menu-open">
                        <li class="nav-item">
                            <a href="{%url 'reception:reception'%}" class="nav-link active">
                                <i class="nav-icon fas fa-circle"></i> Receptions
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{%url 'reception:groups'%}" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Groups
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{%url 'reception:lost'%}" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Lost
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{%url 'reception:new_groups'%}" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> New Groups
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{%url 'reception:first_lesson'%}" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> First & Second
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-tree-view ">
                    <a href="/finance" class="nav-link">
                        <i class="nav-icon fas fa-object-group"></i>
                        <p>Finance</p>
                        <p><i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview menu-open">
                        <li class="nav-item">
                            <a href="/finance" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Payment
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Cashier
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Left money
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/not-paid" class="nav-link">
                                <i class="nav-icon fas fa-circle"></i> Not paid
                            </a>
                        </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
            </ul>
            </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

templates/adminlte/lib/_scripts2.html
<script>
$(document).ready(function () {
  $('.nav-link').click(function(e) {
    $('.nav-link').removeClass('active');
    $(this).addClass("active");
  });
});
</script>

templates/adminlte/lib/_styles2.html
<style>
.rounded-button {
    border:1px solid #aaa;
    padding:1px 5px;
    border-radius:50%
}
</style>